"""Add Feed, Poll, and Messaging models

Revision ID: 066a01d251c0
Revises: 364ecefbd964
Create Date: 2026-03-14 21:24:39.453678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066a01d251c0'
down_revision: Union[str, None] = '364ecefbd964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_polls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('estate_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_conversations_estate_id'), 'feed_conversations', ['estate_id'], unique=False)
    op.create_table('feed_poll_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['feed_polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_conversation_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['feed_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_conversation_participants_conversation_id'), 'feed_conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feed_conversation_participants_user_id'), 'feed_conversation_participants', ['user_id'], unique=False)
    op.create_table('feed_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['feed_conversations.id'], ),
    sa.ForeignKeyConstraint(['from_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_messages_conversation_id'), 'feed_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feed_messages_from_id'), 'feed_messages', ['from_id'], unique=False)
    op.create_table('feed_poll_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['feed_polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('estate_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('reply_to_id', sa.String(), nullable=True),
    sa.Column('repost_id', sa.String(), nullable=True),
    sa.Column('poll_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['feed_polls.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['repost_id'], ['feed_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_posts_author_id'), 'feed_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_feed_posts_estate_id'), 'feed_posts', ['estate_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('favorite_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['favorite_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_favorite_user_id'), 'user_favorites', ['favorite_user_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('feed_post_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_post_likes_post_id'), 'feed_post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_feed_post_likes_user_id'), 'feed_post_likes', ['user_id'], unique=False)
    op.create_table('feed_post_reposts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_post_reposts_post_id'), 'feed_post_reposts', ['post_id'], unique=False)
    op.create_index(op.f('ix_feed_post_reposts_user_id'), 'feed_post_reposts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_post_reposts_user_id'), table_name='feed_post_reposts')
    op.drop_index(op.f('ix_feed_post_reposts_post_id'), table_name='feed_post_reposts')
    op.drop_table('feed_post_reposts')
    op.drop_index(op.f('ix_feed_post_likes_user_id'), table_name='feed_post_likes')
    op.drop_index(op.f('ix_feed_post_likes_post_id'), table_name='feed_post_likes')
    op.drop_table('feed_post_likes')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_favorite_user_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_feed_posts_estate_id'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_author_id'), table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_table('feed_poll_votes')
    op.drop_index(op.f('ix_feed_messages_from_id'), table_name='feed_messages')
    op.drop_index(op.f('ix_feed_messages_conversation_id'), table_name='feed_messages')
    op.drop_table('feed_messages')
    op.drop_index(op.f('ix_feed_conversation_participants_user_id'), table_name='feed_conversation_participants')
    op.drop_index(op.f('ix_feed_conversation_participants_conversation_id'), table_name='feed_conversation_participants')
    op.drop_table('feed_conversation_participants')
    op.drop_table('feed_poll_options')
    op.drop_index(op.f('ix_feed_conversations_estate_id'), table_name='feed_conversations')
    op.drop_table('feed_conversations')
    op.drop_table('feed_polls')
    # ### end Alembic commands ###
