"""Add latitude and longitude to estates

Revision ID: 2511462f8b04
Revises: 4c5a75717a82
Create Date: 2026-01-05 21:52:25.907044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2511462f8b04'
down_revision: Union[str, None] = '4c5a75717a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('estates', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estates', 'longitude')
    op.drop_column('estates', 'latitude')
    # ### end Alembic commands ###
