"""sync_complete_schema_final

Revision ID: 364ecefbd964
Revises: abad02f3f0ba
Create Date: 2026-03-14 15:43:04.337198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364ecefbd964'
down_revision: Union[str, None] = 'abad02f3f0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('bvn_verified', sa.Boolean(), nullable=True))
    # op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'bvn_verified')
    # ### end Alembic commands ###
