"""Add_Block_ID_To_Unit

Revision ID: 3f723dffaaa3
Revises: 55e189533f9e
Create Date: 2025-12-14 15:39:17.370606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f723dffaaa3'
down_revision: Union[str, None] = '55e189533f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE estates CASCADE")
    op.add_column('units', sa.Column('block_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'units', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_column('units', 'block_id')
    # ### end Alembic commands ###
