"""Sync users schema

Revision ID: 4c5a75717a82
Revises: 996770490410
Create Date: 2026-01-04 15:27:00.798160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4c5a75717a82'
down_revision: Union[str, None] = '996770490410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'otp_codes' not in tables:
        op.create_table('otp_codes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    
    if 'two_factor_auth' not in tables:
        op.create_table('two_factor_auth',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('secret', sa.Text(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_two_factor_auth_email'), 'two_factor_auth', ['email'], unique=True)
    if 'bank_details' not in tables:
        op.create_table('bank_details',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('estate_id', sa.String(), nullable=False),
        sa.Column('bank_name', sa.String(), nullable=False),
        sa.Column('account_number', sa.String(), nullable=False),
        sa.Column('account_name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('estate_id')
        )
    
    if 'broadcasts' not in tables:
        op.create_table('broadcasts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('estate_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('target', sa.String(), nullable=False),
        sa.Column('target_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'payouts' not in tables:
        op.create_table('payouts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('estate_id', sa.String(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'service_charge_configs' not in tables:
        op.create_table('service_charge_configs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('estate_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'ONE_OFF', name='servicechargefrequency'), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_service_charge_configs_estate_id'), 'service_charge_configs', ['estate_id'], unique=False)

    if 'webauthn_credentials' not in tables:
        op.create_table('webauthn_credentials',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('credential_id', sa.String(), nullable=False),
        sa.Column('public_key', sa.Text(), nullable=False),
        sa.Column('sign_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('credential_id')
        )

    if 'household_invites' not in tables:
        op.create_table('household_invites',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('relationship', sa.String(), nullable=True),
        sa.Column('profile_image_url', sa.String(), nullable=True),
        sa.Column('status', postgresql.ENUM('ACTIVE', 'USED', 'EXPIRED', 'REVOKED', 'PENDING', 'ACCEPTED', name='invitestatus', create_type=False), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('unit_id', sa.String(), nullable=False),
        sa.Column('invited_by_user_id', sa.String(), nullable=False),
        sa.Column('estate_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
        sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_household_invites_email'), 'household_invites', ['email'], unique=False)
    # Helper to get columns
    def get_col_names(table):
        return [c['name'] for c in inspector.get_columns(table)]

    cols_estates = get_col_names('estates')
    if 'rent_collection_enabled' not in cols_estates:
        op.add_column('estates', sa.Column('rent_collection_enabled', sa.Boolean(), nullable=True))
    if 'home_config' not in cols_estates:
        op.add_column('estates', sa.Column('home_config', sa.JSON(), nullable=True))

    cols_trans = get_col_names('transactions')
    if 'description' not in cols_trans:
        op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    if 'transaction_type' not in cols_trans:
        op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=True))

    cols_units = get_col_names('units')
    if 'rent_amount' not in cols_units:
        op.add_column('units', sa.Column('rent_amount', sa.Integer(), nullable=True))
    if 'next_rent_due' not in cols_units:
        op.add_column('units', sa.Column('next_rent_due', sa.DateTime(timezone=True), nullable=True))
    if 'virtual_account_bank' not in cols_units:
        op.add_column('units', sa.Column('virtual_account_bank', sa.String(), nullable=True))
    if 'virtual_account_number' not in cols_units:
        op.add_column('units', sa.Column('virtual_account_number', sa.String(), nullable=True))
    if 'virtual_account_name' not in cols_units:
        op.add_column('units', sa.Column('virtual_account_name', sa.String(), nullable=True))
    if 'app_fee_pending' not in cols_units:
        op.add_column('units', sa.Column('app_fee_pending', sa.Integer(), nullable=True))

    cols_users = get_col_names('users')
    if 'settings_location_enabled' not in cols_users:
        op.add_column('users', sa.Column('settings_location_enabled', sa.Boolean(), nullable=True))
    if 'settings_push_enabled' not in cols_users:
        op.add_column('users', sa.Column('settings_push_enabled', sa.Boolean(), nullable=True))
    if 'deletion_requested_at' not in cols_users:
        op.add_column('users', sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True))
    if 'bvn_verified' not in cols_users:
        op.add_column('users', sa.Column('bvn_verified', sa.Boolean(), nullable=True))
    if 'kyc_level' not in cols_users:
        op.add_column('users', sa.Column('kyc_level', sa.Integer(), nullable=True))

    cols_vehicles = get_col_names('vehicles')
    if 'vehicle_type' not in cols_vehicles:
        op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=True))

    cols_invites = get_col_names('visitor_invites')
    if 'location_latitude' not in cols_invites:
        op.add_column('visitor_invites', sa.Column('location_latitude', sa.Float(), nullable=True))
    if 'location_longitude' not in cols_invites:
        op.add_column('visitor_invites', sa.Column('location_longitude', sa.Float(), nullable=True))
    if 'location_accuracy' not in cols_invites:
        op.add_column('visitor_invites', sa.Column('location_accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor_invites', 'location_accuracy')
    op.drop_column('visitor_invites', 'location_longitude')
    op.drop_column('visitor_invites', 'location_latitude')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('users', 'kyc_level')
    op.drop_column('users', 'bvn_verified')
    op.drop_column('users', 'deletion_requested_at')
    op.drop_column('users', 'settings_push_enabled')
    op.drop_column('users', 'settings_location_enabled')
    op.drop_column('units', 'app_fee_pending')
    op.drop_column('units', 'virtual_account_name')
    op.drop_column('units', 'virtual_account_number')
    op.drop_column('units', 'virtual_account_bank')
    op.drop_column('units', 'next_rent_due')
    op.drop_column('units', 'rent_amount')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'description')
    op.drop_column('estates', 'home_config')
    op.drop_column('estates', 'rent_collection_enabled')
    op.drop_index(op.f('ix_household_invites_email'), table_name='household_invites')
    op.drop_table('household_invites')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_service_charge_configs_estate_id'), table_name='service_charge_configs')
    op.drop_table('service_charge_configs')
    op.drop_table('payouts')
    op.drop_table('broadcasts')
    op.drop_table('bank_details')
    op.drop_index(op.f('ix_two_factor_auth_email'), table_name='two_factor_auth')
    op.drop_table('two_factor_auth')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
