"""Refactor_Wallet_Models_Retry

Revision ID: 55e189533f9e
Revises: a093539b2874
Create Date: 2025-12-14 15:34:26.489551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e189533f9e'
down_revision: Union[str, None] = 'a093539b2874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom logic: Drop and Recreate bill_assignments/bills/wallet_history to avoid conflicts
    # Using CASCADE to handle dependencies automatically
    op.execute("DROP TABLE IF EXISTS bill_assignments CASCADE")
    op.execute("DROP TABLE IF EXISTS wallet_history CASCADE")
    # Bills table might be needed? No, bills table structure didn't change much but assignments did.
    # If we dropped assignments, we can keep bills if it matches? 
    # But for safety and cleaner schema, let's keep bills if checking its columns.
    # Actually, let's just drop assignments and wallet history as they are the ones changing significantly.
    
    op.create_table('bill_assignments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('bill_id', sa.String(), nullable=False),
        sa.Column('unit_id', sa.String(), nullable=False),
        sa.Column('amount_paid', sa.Integer(), default=0),
        sa.Column('status', sa.String(), default='PENDING'),
        sa.ForeignKeyConstraint(['bill_id'], ['bills.id']),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('wallet_history',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('unit_id', sa.String(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('unit_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'units', ['unit_id'], ['id'])
    op.add_column('units', sa.Column('wallet_balance', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('units_block_id_fkey'), 'units', type_='foreignkey')
    op.drop_column('units', 'block_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('units_block_id_fkey'), 'units', 'blocks', ['block_id'], ['id'])
    op.drop_column('units', 'wallet_balance')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'unit_id')
    op.add_column('bill_assignments', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bill_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('bill_assignments_user_id_fkey'), 'bill_assignments', 'users', ['user_id'], ['id'])
    op.drop_column('bill_assignments', 'unit_id')
    op.drop_table('wallet_history')
    # ### end Alembic commands ###
