"""Add SavedCard and BankTransferReference

Revision ID: 68152d5f4ea8
Revises: 32f4448d8591
Create Date: 2026-01-12 20:58:57.058283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68152d5f4ea8'
down_revision: Union[str, None] = '32f4448d8591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'saved_cards' not in tables:
        op.create_table('saved_cards',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('authorization_code', sa.String(), nullable=False),
        sa.Column('last4', sa.String(), nullable=False),
        sa.Column('brand', sa.String(), nullable=False),
        sa.Column('exp_month', sa.String(), nullable=False),
        sa.Column('exp_year', sa.String(), nullable=False),
        sa.Column('bin', sa.String(), nullable=True),
        sa.Column('bank', sa.String(), nullable=True),
        sa.Column('channel', sa.String(), nullable=True),
        sa.Column('signature', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_saved_cards_user_id'), 'saved_cards', ['user_id'], unique=False)

    if 'bank_transfer_references' not in tables:
        op.create_table('bank_transfer_references',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('reference', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('estate_id', sa.String(), nullable=False),
        sa.Column('unit_id', sa.String(), nullable=False),
        sa.Column('service_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=False),
        sa.Column('provider_id', sa.String(), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('paystack_customer_code', sa.String(), nullable=True),
        sa.Column('account_number', sa.String(), nullable=True),
        sa.Column('bank_name', sa.String(), nullable=True),
        sa.Column('account_name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_bank_transfer_references_reference'), 'bank_transfer_references', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transfer_references_reference'), table_name='bank_transfer_references')
    op.drop_table('bank_transfer_references')
    op.drop_index(op.f('ix_saved_cards_user_id'), table_name='saved_cards')
    op.drop_table('saved_cards')
    # ### end Alembic commands ###
