"""Add access_code and sync webhook_logs

Revision ID: 849266eb7f47
Revises: ae06497884ed
Create Date: 2026-01-22 12:32:42.446330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849266eb7f47'
down_revision: Union[str, None] = 'ae06497884ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_access_code'), 'users', ['access_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_access_code'), table_name='users')
    op.drop_column('users', 'access_code')
    # ### end Alembic commands ###
