"""Add_Visitor_Invites

Revision ID: 94c16b484989
Revises: 4897f251e592
Create Date: 2025-12-13 22:43:46.513448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c16b484989'
down_revision: Union[str, None] = '4897f251e592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=False),
    sa.Column('visitor_phone', sa.String(), nullable=True),
    sa.Column('access_code', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', 'REVOKED', name='invitestatus'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('estate_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_invites_access_code'), 'visitor_invites', ['access_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_invites_access_code'), table_name='visitor_invites')
    op.drop_table('visitor_invites')
    # ### end Alembic commands ###
