"""Add DeviceToken Model

Revision ID: 996770490410
Revises: 62f6cdd80589
Create Date: 2026-01-04 15:16:08.585950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '996770490410'
down_revision: Union[str, None] = '62f6cdd80589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added: Create device_tokens table
    op.create_table('device_tokens',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('platform', sa.String(), nullable=True, server_default="ios"),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('device_tokens_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('device_tokens_pkey'))
    )
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=False)
    
    # Do NOT drop bank_transfer_references (keeping existing data)
    # op.drop_index(op.f('ix_bank_transfer_references_reference'), table_name='bank_transfer_references')
    # op.drop_table('bank_transfer_references')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    
    # op.create_table('bank_transfer_references', ...) # Skipped since we didn't drop it
    # ### end Alembic commands ###
