"""Add_Bills

Revision ID: a093539b2874
Revises: 65bc43debfc4
Create Date: 2025-12-14 15:19:56.707423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a093539b2874'
down_revision: Union[str, None] = '65bc43debfc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estate_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_assignments')
    op.drop_table('bills')
    # ### end Alembic commands ###
