"""Add attachments to complaints

Revision ID: a65dbd6eed0f
Revises: 3f723dffaaa3
Create Date: 2025-12-16 22:01:47.000941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65dbd6eed0f'
down_revision: Union[str, None] = '3f723dffaaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'attachments')
    # ### end Alembic commands ###
