"""add_digital_id_columns_unified

Revision ID: abad02f3f0ba
Revises: b1d6e9c4a201
Create Date: 2026-03-14 15:31:18.099948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abad02f3f0ba'
down_revision: Union[str, None] = 'b1d6e9c4a201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_activity_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('invite_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_push_token', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['visitor_invites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_activity_tokens_activity_id'), 'live_activity_tokens', ['activity_id'], unique=True)
    op.drop_column('estates', 'latitude')
    op.drop_column('estates', 'longitude')
    op.drop_constraint(op.f('kyc_sessions_reference_key'), 'kyc_sessions', type_='unique')
    op.add_column('users', sa.Column('digital_id_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('digital_id_refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'deletion_requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When user requested account deletion',
               existing_nullable=True)
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Personal wallet balance (replaces shared unit wallet)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # Removed active_token_id alter_column to prevent transaction abort
    op.execute('DROP INDEX IF EXISTS idx_users_scheduled_deletion')
    op.create_index(op.f('ix_users_digital_id_token'), 'users', ['digital_id_token'], unique=True)
    # op.drop_column('users', 'is_deleted')
    # op.drop_column('users', 'scheduled_deletion_date')
    # op.alter_column('verification_logs', 'verified_by_user_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('verification_logs', 'verification_method',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_foreign_key(None, 'verification_logs', 'visitor_invites', ['invite_id'], ['id'])
    # op.create_foreign_key(None, 'verification_logs', 'estates', ['estate_id'], ['id'])
    # op.create_foreign_key(None, 'verification_logs', 'users', ['verified_by_user_id'], ['id'])
    # op.create_foreign_key(None, 'verification_logs', 'users', ['guard_id'], ['id'])
    op.drop_constraint(op.f('wallet_profiles_user_id_key'), 'wallet_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('wallet_profiles_user_id_key'), 'wallet_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'verification_logs', type_='foreignkey')
    op.drop_constraint(None, 'verification_logs', type_='foreignkey')
    op.drop_constraint(None, 'verification_logs', type_='foreignkey')
    op.drop_constraint(None, 'verification_logs', type_='foreignkey')
    op.alter_column('verification_logs', 'verification_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('verification_logs', 'verified_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('scheduled_deletion_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When account will be permanently deleted (7 days after request)'))
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='True if account has been permanently deleted'))
    op.drop_index(op.f('ix_users_digital_id_token'), table_name='users')
    op.create_index(op.f('idx_users_scheduled_deletion'), 'users', ['scheduled_deletion_date'], unique=False, postgresql_where='((is_deleted = false) AND (scheduled_deletion_date IS NOT NULL))')
    op.alter_column('users', 'active_token_id',
               existing_type=sa.VARCHAR(),
               comment='UUID of the currently valid token for session tracking',
               existing_nullable=True)
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.INTEGER(),
               comment='Personal wallet balance (replaces shared unit wallet)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'deletion_requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When user requested account deletion',
               existing_nullable=True)
    op.drop_column('users', 'digital_id_refreshed_at')
    op.drop_column('users', 'digital_id_token')
    op.create_unique_constraint(op.f('kyc_sessions_reference_key'), 'kyc_sessions', ['reference'], postgresql_nulls_not_distinct=False)
    op.add_column('estates', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('estates', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_live_activity_tokens_activity_id'), table_name='live_activity_tokens')
    op.drop_table('live_activity_tokens')
    # ### end Alembic commands ###
