"""Add payment_reference to vehicles

Revision ID: b406d0294c10
Revises: a65dbd6eed0f
Create Date: 2025-12-16 22:03:25.937469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b406d0294c10'
down_revision: Union[str, None] = 'a65dbd6eed0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('payment_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'payment_reference')
    # ### end Alembic commands ###
