"""Add vehicle_type to Vehicle

Revision ID: ba15e0908bf9
Revises: f2df0776510e
Create Date: 2025-12-16 22:46:00.550699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba15e0908bf9'
down_revision: Union[str, None] = 'f2df0776510e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_type')
    # ### end Alembic commands ###
