"""Add gender expected_guests and recurring invite type

Revision ID: c4c66f8f6758
Revises: f516cac80eec
Create Date: 2026-02-14 11:37:52.707612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4c66f8f6758'
down_revision: Union[str, None] = 'f516cac80eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'next_rent_due',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'deletion_requested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_balance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('transaction_pin_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('active_token_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'deletion_requested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('user_units', sa.Column('role', postgresql.ENUM('ADMIN', 'SPOUSE', 'CHILD', 'PARENT', 'RELATIVE', 'STAFF', 'OTHER', 'sub_admin', 'admin', 'spouse', 'child', 'parent', 'relative', 'staff', 'other', name='householdrole'), autoincrement=False, nullable=True))
    op.alter_column('units', 'next_rent_due',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('device_tokens', sa.Column('active_token_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
