"""Add unit_id and type to visitor_invites

Revision ID: eb19ed11dc0d
Revises: b406d0294c10
Create Date: 2025-12-16 22:10:40.748614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb19ed11dc0d'
down_revision: Union[str, None] = 'b406d0294c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum manually
    invite_type = sa.Enum('SINGLE', 'GROUP', name='invitetype')
    invite_type.create(op.get_bind(), checkfirst=True)
    
    op.add_column('visitor_invites', sa.Column('invite_type', sa.Enum('SINGLE', 'GROUP', name='invitetype'), nullable=True))
    op.add_column('visitor_invites', sa.Column('unit_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'visitor_invites', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitor_invites', type_='foreignkey')
    op.drop_column('visitor_invites', 'unit_id')
    op.drop_column('visitor_invites', 'invite_type')
    
    # Drop Enum
    invite_type = sa.Enum('SINGLE', 'GROUP', name='invitetype')
    invite_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
